from django.db import models


class House(models.Model):
    GrLivArea = models.IntegerField()
    YearBuilt = models.IntegerField()
    GarageCars = models.IntegerField()
    TotalBsmtSF = models.IntegerField()
    FullBath = models.IntegerField()
    OverallQual = models.IntegerField()
    Neighborhood = models.CharField(max_length=50)
    predicted_price = models.FloatField(null=True, blank=True)

class DiabetesPrediction(models.Model):
    Pregnancies = models.IntegerField()
    Glucose = models.IntegerField()
    BloodPressure = models.IntegerField()
    SkinThickness = models.IntegerField()
    Insulin = models.IntegerField()
    BMI = models.FloatField()
    DiabetesPedigreeFunction = models.FloatField()
    Age = models.IntegerField()
    predicted_label = models.CharField(max_length=10, blank=True)
    probability = models.FloatField(null=True, blank=True)

class Bank(models.Model):
    person_age = models.FloatField()
    person_gender = models.CharField(max_length=20)
    person_education = models.CharField(max_length=50)
    person_income = models.FloatField()
    person_emp_exp = models.IntegerField()
    person_home_ownership = models.CharField(max_length=20)
    loan_famnt = models.FloatField()
    loan_intent = models.CharField(max_length=50)
    loan_int_rate = models.FloatField()
    loan_percent_income = models.FloatField()
    cb_person_cred_hist_length = models.FloatField()
    credit_score = models.IntegerField()
    previous_loan_defaults_on_file = models.CharField(max_length=10)
    predicted_result = models.CharField(max_length=20, null=True, blank=True)



class Titanic(models.Model):
    Pclass = models.IntegerField()
    Sex = models.CharField(max_length=10)
    age = models.IntegerField()
    Fare = models.FloatField()
    SibSp = models.IntegerField(default=0)
    Parch = models.IntegerField(default=0)
    embarked = models.CharField(max_length=20)
    predicted_result = models.CharField(max_length=20, null=True, blank=True)


class Avocado(models.Model):
    firmness = models.FloatField()
    hue = models.IntegerField()
    saturation = models.IntegerField()
    brightness = models.IntegerField()
    color_category = models.CharField(max_length=20)
    sound_db = models.IntegerField()
    weight_g = models.IntegerField()
    size_cm3 = models.IntegerField()
    predicted_label = models.CharField(max_length=30, null=True, blank=True)



class Telco(models.Model):
    gender = models.CharField(max_length=20)
    SeniorCitizen = models.IntegerField()
    Partner = models.CharField(max_length=10)
    Dependents = models.CharField(max_length=10)
    tenure = models.IntegerField()
    PhoneService = models.CharField(max_length=10)
    MultipleLines = models.CharField(max_length=20)
    InternetService = models.CharField(max_length=20)
    OnlineSecurity = models.CharField(max_length=30)
    OnlineBackup = models.CharField(max_length=30)
    DeviceProtection = models.CharField(max_length=30)
    TechSupport = models.CharField(max_length=30)
    StreamingTV = models.CharField(max_length=30)
    StreamingMovies = models.CharField(max_length=30)
    Contract = models.CharField(max_length=20)
    PaperlessBilling = models.CharField(max_length=10)
    PaymentMethod = models.CharField(max_length=50)
    MonthlyCharges = models.IntegerField()
    TotalCharges = models.IntegerField()
    predicted_label = models.CharField(max_length=20, null=True, blank=True)
    probability = models.FloatField(null=True, blank=True)

class Student(models.Model):
    math_score = models.IntegerField()
    reading_score = models.IntegerField()
    gender = models.CharField(max_length=10)
    race_ethnicity = models.CharField(max_length=20)
    parent_education = models.CharField(max_length=50)
    lunch = models.CharField(max_length=20)
    test_preparation = models.CharField(max_length=20)

    predicted_score = models.FloatField(null=True, blank=True)

class HREmployee(models.Model):
    Age = models.IntegerField(max_length=100)
    BusinessTravel = models.CharField(max_length=50)
    DailyRate = models.IntegerField()
    Department = models.CharField(max_length=50)
    DistanceFromHome = models.IntegerField(max_length=60)
    Education = models.IntegerField(max_length=50)
    EducationField = models.CharField()
    EnvironmentSatisfaction = models.IntegerField(max_length=50)
    Gender = models.CharField(max_length=10)
    HourlyRate = models.IntegerField(max_length=100)
    JobInvolvement = models.IntegerField(max_length=40)
    JobLevel = models.IntegerField()
    JobRole = models.CharField()
    JobSatisfaction = models.IntegerField(max_length=50)
    MaritalStatus = models.CharField()
    MonthlyIncome = models.IntegerField()
    MonthlyRate = models.IntegerField()
    NumCompaniesWorked = models.IntegerField(max_length=50)
    OverTime = models.CharField()
    PercentSalaryHike = models.IntegerField(max_length=100)
    PerformanceRating = models.IntegerField(max_length=5)
    RelationshipSatisfaction = models.IntegerField(max_length=10)
    StockOptionLevel = models.IntegerField(max_length=10)
    TotalWorkingYears = models.IntegerField(max_length=50)
    TrainingTimesLastYear = models.IntegerField(max_length=50)
    WorkLifeBalance = models.IntegerField(max_length=50)
    YearsAtCompany = models.IntegerField(max_length=50)
    YearsInCurrentRole = models.IntegerField(max_length=30)
    YearsSinceLastPromotion = models.IntegerField(max_length=10)
    YearsWithCurrManager = models.IntegerField(max_length=20)